package org.persistence.entities;// default package

// Generated Mar 14, 2023, 1:07:33 AM by Hibernate Tools 6.1.7.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Cart generated by hbm2java
 */
@Entity
@Table(name = "cart", catalog = "talktech")
public class Cart implements java.io.Serializable {

    private Integer cartId;
    private Integer userId;
    private BigDecimal totalPrice;
    private Set<CartItems> cartItems = new HashSet(0);

    public Cart() {
    }

    public Cart(Integer userId, BigDecimal totalPrice, Set<CartItems> cartItems) {
        this.userId = userId;
        this.totalPrice = totalPrice;
        this.cartItems = cartItems;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "CartID", unique = true, nullable = false)
    public Integer getCartId() {
        return this.cartId;
    }

    public void setCartId(Integer cartId) {
        this.cartId = cartId;
    }

    @Column(name = "UserID")
    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Column(name = "TotalPrice", precision = 10, scale = 2)
    public BigDecimal getTotalPrice() {
        return this.totalPrice;
    }

    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cart")
    public Set<CartItems> getCartItems() {
        return this.cartItems;
    }

    public void setCartItems(Set<CartItems> cartItems) {
        this.cartItems = cartItems;
    }

}
