package org.persistence.entities;// default package
// Generated Mar 14, 2023, 1:07:33 AM by Hibernate Tools 6.1.7.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name="order"
    ,catalog="talktech"
)
public class Order  implements java.io.Serializable {


     private int orderId;
     private User user;
     private Timestamp orderDate;
     private BigDecimal totalPrice;
     private Set<OrderItems> orderItems = new HashSet(0);

    public Order() {
    }

	
    public Order(int orderId) {
        this.orderId = orderId;
    }
    public Order(int orderId, User user, Timestamp orderDate, BigDecimal totalPrice, Set<OrderItems> orderItems) {
       this.orderId = orderId;
       this.user = user;
       this.orderDate = orderDate;
       this.totalPrice = totalPrice;
       this.orderItems = orderItems;
    }
   
     @Id 

    
    @Column(name="OrderID", unique=true, nullable=false)
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="UserID")
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="OrderDate", length=19)
    public Timestamp getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Timestamp orderDate) {
        this.orderDate = orderDate;
    }

    
    @Column(name="TotalPrice", precision=10, scale=2)
    public BigDecimal getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="order")
    public Set<OrderItems> getOrderitemses() {
        return this.orderItems;
    }
    
    public void setOrderitemses(Set<OrderItems> orderItems) {
        this.orderItems = orderItems;
    }




}


