package org.persistence.entities;// default package
// Generated Mar 14, 2023, 1:07:33 AM by Hibernate Tools 6.1.7.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name="product"
    ,catalog="talktech"
)
public class Product  implements java.io.Serializable {
     private Integer productId;
     private String name;
     private String description;
     private BigDecimal price;
     private Integer quantity;
     private Integer categoryId;
     private Set<CartItems> cartItems = new HashSet(0);
     private Set<OrderItems> orderItems = new HashSet(0);

    public Product() {
    }

    public Product(String name, String description, BigDecimal price, Integer quantity, Integer categoryId, Set<CartItems> cartItems, Set<OrderItems> orderItems) {
       this.name = name;
       this.description = description;
       this.price = price;
       this.quantity = quantity;
       this.categoryId = categoryId;
       this.cartItems = cartItems;
       this.orderItems = orderItems;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ProductID", unique=true, nullable=false)
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    
    @Column(name="Name", length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Description", length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="Price", precision=10, scale=2)
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    
    @Column(name="Quantity")
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="CategoryID")
    public Integer getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="product")
    public Set<CartItems> getCartItems() {
        return this.cartItems;
    }
    
    public void setCartItems(Set<CartItems> cartItems) {
        this.cartItems = cartItems;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="product")
    public Set<OrderItems> getOrderItems() {
        return this.orderItems;
    }
    
    public void setOrderItems(Set<OrderItems> orderItems) {
        this.orderItems = orderItems;
    }




}


