package org.persistence.entities;// default package
// Generated Mar 14, 2023, 1:07:33 AM by Hibernate Tools 6.1.7.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="talktech"
    , uniqueConstraints = @UniqueConstraint(columnNames="Email") 
)
public class User  implements java.io.Serializable {


     private Integer userId;
     private String name;
     private String email;
     private String password;
     private String job;
     private BigDecimal creditLimit;
     private String address;
     private String interests;
     private String userType="Customer";
     private Set<Order> orders = new HashSet(0);

    public User() {
    }

    public User(String name, String email, String password, String job, BigDecimal creditLimit, String address, String interests, String userType, Set<Order>  orders) {
       this.name = name;
       this.email = email;
       this.password = password;
       this.job = job;
       this.creditLimit = creditLimit;
       this.address = address;
       this.interests = interests;
       this.userType = "Customer";
       this.orders = orders;
    }
    public User(String email){
        this.email = email;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="UserID", unique=true, nullable=false)
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    
    @Column(name="Name", length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Email", unique=true, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="Password", length=50)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="Job", length=50)
    public String getJob() {
        return this.job;
    }
    
    public void setJob(String job) {
        this.job = job;
    }

    
    @Column(name="CreditLimit", precision=10, scale=2)
    public BigDecimal getCreditLimit() {
        return this.creditLimit;
    }
    
    public void setCreditLimit(BigDecimal creditLimit) {
        this.creditLimit = creditLimit;
    }

    
    @Column(name="Address", length=100)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="Interests", length=100)
    public String getInterests() {
        return this.interests;
    }
    
    public void setInterests(String interests) {
        this.interests = interests;
    }

    
    @Column(name="UserType", length=50)
    public String getUserType() {
        return this.userType;
    }
    
    public void setUserType(String userType) {
        this.userType = userType;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Order>  getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set<Order> orders) {
        this.orders = orders;
    }




}


